name: build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.10
      uses: actions/setup-node@v1
      with:
        node-version: '18.10'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: arbhutale/personal-UI/react-ui
        registry: docker.pkg.github.com
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
        dockerfile: Dockerfile-prod
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        envs: GIT_USERNAME, GIT_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login -u arbhutale -p ${{ secrets.GIT_TOKEN }} docker.pkg.github.com
          docker pull docker.pkg.github.com/arbhutale/personal-ui/react-ui:latest
          docker run -dit -p 80:80 docker.pkg.github.com/arbhutale/personal-ui/react-ui:latest
